### ISSUE TITLE
Issue when running code.

### ISSUE THREAD

**Issue by jhuvehicle** [JonasGeiping/poisoning-gradient-matching#5]
Hello Jonas,

I am obtaining the following issue:

Currently evaluating -------------------------------:
Friday, 09. February 2024 10:29PM
Namespace(net=['ResNet18'], dataset='CIFAR10', recipe='gradient-matching', threatmodel='single-class', poisonkey=None, modelkey=None, deterministic=False, eps=16, budget=0.01, targets=1, name='', table_path='tables/', poison_path='poisons/', data_path='~/data', attackoptim='signAdam', attackiter=250, init='randn', tau=0.1, scheduling=True, target_criterion='cross-entropy', restarts=8, pbatch=512, pshuffle=False, paugment=True, data_aug='default', full_data=False, adversarial=0, ensemble=1, stagger=False, step=False, max_epoch=None, ablation=1.0, loss='similarity', centreg=0, normreg=0, repel=0, nadapt=2, clean_grad=False, vruns=1, vnet=None, retrain_from_init=False, pretrained=False, optimization='conservative', epochs=None, noaugment=False, gradient_noise=None, gradient_clip=None, lmdb_path=None, cache_dataset=False, benchmark='', benchmark_idx=0, dryrun=False, save=None, local_rank=None)
CPUs: 4, GPUs: 1 on 9edab406bc1c.
GPU : Tesla T4
ResNet18 model initialized with random key 3006739989.
Downloading https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz to /root/data/cifar-10-python.tar.gz
100% 170498071/170498071 [00:10<00:00, 15866478.66it/s]
Extracting /root/data/cifar-10-python.tar.gz to /root/data
Data mean is [0.4914672374725342, 0.4822617471218109, 0.4467701315879822], 
Data std  is [0.24703224003314972, 0.24348513782024384, 0.26158785820007324].
Files already downloaded and verified
Data is loaded with 4 workers.
Initializing Poison data (chosen images, examples, targets, labels) with random seed 3081592952
Poisoning setup generated for threat model single-class and budget of 1.0% - 500 images:
--Target images drawn from class frog with ids [7591].
--Target images assigned intended class ship.
--Poison images drawn from class ship.
Starting clean training ...
Epoch: 0  | lr: 0.1000 | Training    loss is  2.0856, train acc:  25.70% | Validation   loss is  1.5819, valid acc:  40.90% | 
Epoch: 0  | lr: 0.1000 | Target adv. loss is  6.2353, fool  acc:   0.00% | Target orig. loss is  1.4629, orig. acc:   0.00% | 
Epoch: 1  | lr: 0.1000 | Training    loss is  1.4694, train acc:  45.79% | 
Epoch: 2  | lr: 0.1000 | Training    loss is  1.1966, train acc:  56.84% | 
Epoch: 3  | lr: 0.1000 | Training    loss is  0.9275, train acc:  66.95% | 
Epoch: 4  | lr: 0.1000 | Training    loss is  0.7451, train acc:  73.99% | 
Epoch: 5  | lr: 0.1000 | Training    loss is  0.6461, train acc:  77.69% | 
Epoch: 6  | lr: 0.1000 | Training    loss is  0.5837, train acc:  79.75% | 
Epoch: 7  | lr: 0.1000 | Training    loss is  0.5418, train acc:  81.40% | 
Epoch: 8  | lr: 0.1000 | Training    loss is  0.5118, train acc:  82.26% | 
Epoch: 9  | lr: 0.1000 | Training    loss is  0.4894, train acc:  83.26% | 
Epoch: 10 | lr: 0.1000 | Training    loss is  0.4702, train acc:  83.99% | Validation   loss is  0.6481, valid acc:  79.01% | 
Epoch: 10 | lr: 0.1000 | Target adv. loss is 12.3570, fool  acc:   0.00% | Target orig. loss is  0.0085, orig. acc: 100.00% | 
Epoch: 11 | lr: 0.1000 | Training    loss is  0.4568, train acc:  84.38% | 
Epoch: 12 | lr: 0.1000 | Training    loss is  0.4420, train acc:  84.76% | 
Epoch: 13 | lr: 0.0100 | Training    loss is  0.4327, train acc:  85.17% | 
Epoch: 14 | lr: 0.0100 | Training    loss is  0.2746, train acc:  90.73% | 
Epoch: 15 | lr: 0.0100 | Training    loss is  0.2241, train acc:  92.34% | 
Epoch: 16 | lr: 0.0100 | Training    loss is  0.2001, train acc:  93.13% | 
Epoch: 17 | lr: 0.0100 | Training    loss is  0.1795, train acc:  93.87% | 
Epoch: 18 | lr: 0.0100 | Training    loss is  0.1683, train acc:  94.29% | 
Epoch: 19 | lr: 0.0100 | Training    loss is  0.1568, train acc:  94.74% | 
Epoch: 20 | lr: 0.0100 | Training    loss is  0.1461, train acc:  95.03% | Validation   loss is  0.2616, valid acc:  91.47% | 
Epoch: 20 | lr: 0.0100 | Target adv. loss is 10.4137, fool  acc:   0.00% | Target orig. loss is  0.0551, orig. acc: 100.00% | 
Epoch: 21 | lr: 0.0100 | Training    loss is  0.1352, train acc:  95.47% | 
Epoch: 22 | lr: 0.0100 | Training    loss is  0.1277, train acc:  95.55% | 
Epoch: 23 | lr: 0.0010 | Training    loss is  0.1212, train acc:  95.92% | 
Epoch: 24 | lr: 0.0010 | Training    loss is  0.0914, train acc:  97.00% | 
Epoch: 25 | lr: 0.0010 | Training    loss is  0.0803, train acc:  97.47% | 
Epoch: 26 | lr: 0.0010 | Training    loss is  0.0781, train acc:  97.57% | 
Epoch: 27 | lr: 0.0010 | Training    loss is  0.0737, train acc:  97.70% | 
Epoch: 28 | lr: 0.0010 | Training    loss is  0.0701, train acc:  97.82% | 
Epoch: 29 | lr: 0.0010 | Training    loss is  0.0698, train acc:  97.81% | 
Epoch: 30 | lr: 0.0010 | Training    loss is  0.0652, train acc:  97.85% | Validation   loss is  0.2461, valid acc:  92.31% | 
Epoch: 30 | lr: 0.0010 | Target adv. loss is 12.1269, fool  acc:   0.00% | Target orig. loss is  0.0015, orig. acc: 100.00% | 
Epoch: 31 | lr: 0.0010 | Training    loss is  0.0618, train acc:  98.12% | 
Epoch: 32 | lr: 0.0010 | Training    loss is  0.0621, train acc:  98.05% | 
Epoch: 33 | lr: 0.0010 | Training    loss is  0.0587, train acc:  98.22% | 
Epoch: 34 | lr: 0.0001 | Training    loss is  0.0560, train acc:  98.29% | 
Epoch: 35 | lr: 0.0001 | Training    loss is  0.0552, train acc:  98.29% | 
Epoch: 36 | lr: 0.0001 | Training    loss is  0.0520, train acc:  98.49% | 
Epoch: 37 | lr: 0.0001 | Training    loss is  0.0530, train acc:  98.41% | 
Epoch: 38 | lr: 0.0001 | Training    loss is  0.0547, train acc:  98.34% | 
Epoch: 39 | lr: 0.0001 | Training    loss is  0.0527, train acc:  98.41% | Validation   loss is  0.2448, valid acc:  92.37% | 
Epoch: 39 | lr: 0.0001 | Target adv. loss is 12.5681, fool  acc:   0.00% | Target orig. loss is  0.0007, orig. acc: 100.00% | 
Starting brewing procedure ...
Target Grad Norm is 144.56398010253906
Iteration 0: Target loss is 0.8051, Poison clean acc is 89.20%
Traceback (most recent call last):
  File "/content/poisoning-gradient-matching/brew_poison.py", line 35, in <module>
    poison_delta = witch.brew(model, data)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 42, in brew
    poison_delta = self._brew(victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 65, in _brew
    poison_delta, target_losses = self._run_trial(victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 150, in _run_trial
    loss, prediction = self._batched_step(poison_delta, poison_bounds, example, victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 242, in _batched_step
    poison_delta.grad[poison_slices] = delta_slice.grad.detach().to(device=torch.device('cpu'))
TypeError: 'NoneType' object does not support item assignment

**Comment by jhuvehicle** [comment]
I have attached the google colab code here.

[Recent_Run_2_9_2024.zip](https://github.com/JonasGeiping/poisoning-gradient-matching/files/14226980/Recent_Run_2_9_2024.zip)

**Comment by jhuvehicle** [comment]
One sec, I think you posted that in another issue.

**Comment by jhuvehicle** [comment]
This worked when I looked at the other issue in the repo. Closing this.
