### ISSUE TITLE
Trying to run the tiny image dataset and I obtain this error.

### ISSUE THREAD

**Issue by jhuvehicle** [JonasGeiping/poisoning-gradient-matching#6]
Starting brewing procedure ...
Target Grad Norm is 282.13812255859375
Iteration 0: Target loss is 0.8387, Poison clean acc is 93.20%
Traceback (most recent call last):
  File "/content/poisoning-gradient-matching/brew_poison.py", line 35, in <module>
    poison_delta = witch.brew(model, data)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 42, in brew
    poison_delta = self._brew(victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 65, in _brew
    poison_delta, target_losses = self._run_trial(victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 150, in _run_trial
    loss, prediction = self._batched_step(poison_delta, poison_bounds, example, victim, kettle)
  File "/content/poisoning-gradient-matching/forest/witchcoven/witch_base.py", line 242, in _batched_step
    poison_delta.grad[poison_slices] = delta_slice.grad.detach().to(device=torch.device('cpu'))
TypeError: 'NoneType' object does not support item assignment
0:52:15.669996

**Comment by jhuvehicle** [comment]
Not sure what changes I should make @JonasGeiping @lhfowl

**Comment by JonasGeiping** [comment]
Just to confirm, did you try https://github.com/JonasGeiping/poisoning-gradient-matching/issues/4#issuecomment-1880547544?

**Comment by jhuvehicle** [comment]
I did, this was using the default parameters, using the command you provide in your git it ran successfully.

**Comment by jhuvehicle** [comment]
Closing this, it may have been a google colab issue and not a code issue.
